# Builds, publishes and creates an artifact for:
# - Swabbr.API (ASP.Net Core Web API project)
# - Swabbr.AzureFunctions (Azure Functions project)
# 
# This performs a separate build for each in order to trigger the static analysis.

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet

- task: NuGetCommand@2
  displayName: Restore packages
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build Swabbr.Api
  inputs:
    command: 'build'
    publishWebProjects: false
    projects: '**/Swabbr.Api.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish Swabbr.Api
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Swabbr.Api.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/web'

- task: DotNetCoreCLI@2
  displayName: Build Swabbr.AzureFunctions
  inputs:
    command: 'build'
    publishWebProjects: false
    projects: '**/Swabbr.AzureFunctions.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish Swabbr.AzureFunctions
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Swabbr.AzureFunctions.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/func -r win-x64'

- task: PublishBuildArtifacts@1
  displayName: Publish Swabbr.Api build artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/web'
    ArtifactName: 'web'

- task: PublishBuildArtifacts@1
  displayName: Publish Swabbr.AzureFunctions build artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/func'
    ArtifactName: 'func'