using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;

namespace Swabbr.Api.ViewModels
{
    /// <summary>
    ///     Input model for placing a reaction.
    /// </summary>
    public class ReactionInputModel
    {
        /// <summary>
        ///     Id of the vlog the reaction belongs to.
        /// </summary>
        [Required]
        public Guid TargetVlogId { get; set; }

        /// <summary>
        ///     Id of the posted reaction.
        /// </summary>
        /// <remarks>
        ///     This guid should be generated by the client
        ///     and should match the filename of the uploaded
        ///     reaction video file.
        /// </remarks>
        [Required]
        public Guid ReactionId { get; set; }

        /// <summary>
        ///     Indicates whether this reaction is 
        ///     public or private.
        /// </summary>
        public bool IsPrivate { get; set; }
    }
}
